/**
 * Helper utilities for Chrome extension E2E testing
 */

import { chromium, type BrowserContext, type Page } from '@playwright/test';
import path from 'path';

/**
 * Extension configuration
 */
export const EXTENSION_CONFIG = {
  distPath: path.join(__dirname, '../../../dist'),
  baseUrl: 'https://app.trainingpeaks.com',
};

/**
 * Launch Chrome with extension loaded
 *
 * @returns Browser context with extension loaded
 */
export async function launchExtension(): Promise<BrowserContext> {
  const context = await chromium.launchPersistentContext('', {
    headless: false, // Extensions require headed mode
    args: [
      `--disable-extensions-except=${EXTENSION_CONFIG.distPath}`,
      `--load-extension=${EXTENSION_CONFIG.distPath}`,
      '--no-sandbox',
      '--disable-dev-shm-usage', // Helps in CI environments
    ],
    // Viewport size (default popup size)
    viewport: { width: 1280, height: 720 },
  });

  return context;
}

/**
 * Get extension ID from manifest
 * The extension ID is generated by Chrome based on the extension path
 *
 * @param context Browser context
 * @returns Extension ID or null
 */
export async function getExtensionId(
  context: BrowserContext
): Promise<string | null> {
  // Navigate to chrome://extensions in a new page
  const page = await context.newPage();
  await page.goto('chrome://extensions');

  // Get extension ID from the page
  // Note: This is a workaround and may not work in all cases
  const extensionId = await page.evaluate(() => {
    const extensions = document.querySelectorAll('extensions-item');
    for (const ext of Array.from(extensions)) {
      const name = ext.shadowRoot?.querySelector('#name')?.textContent;
      if (name?.includes('TrainingPeaks')) {
        return ext.getAttribute('id');
      }
    }
    return null;
  });

  await page.close();
  return extensionId;
}

/**
 * Open extension popup
 *
 * @param context Browser context
 * @param extensionId Extension ID (optional, will auto-detect)
 * @returns Popup page
 */
export async function openPopup(
  context: BrowserContext,
  extensionId?: string
): Promise<Page> {
  const id = extensionId || (await getExtensionId(context));

  if (!id) {
    throw new Error('Could not find extension ID');
  }

  // Open popup by navigating to popup URL
  const popupUrl = `chrome-extension://${id}/src/popup/index.html`;
  const page = await context.newPage();
  await page.goto(popupUrl);

  return page;
}

/**
 * Wait for extension to intercept token
 *
 * @param page Page object
 * @param timeout Max wait time in ms
 * @returns True if token was intercepted
 */
export async function waitForTokenInterception(
  page: Page,
  timeout: number = 5000
): Promise<boolean> {
  return page.waitForFunction(
    () => {
      return window.localStorage.getItem('auth_token') !== null;
    },
    { timeout }
  );
}

/**
 * Check authentication status in extension storage
 *
 * @param context Browser context
 * @returns True if authenticated
 */
export async function isExtensionAuthenticated(
  context: BrowserContext
): Promise<boolean> {
  // This would require accessing chrome.storage from a background script context
  // For now, we check by opening the popup and reading the UI
  const popup = await openPopup(context);

  const isAuth = await popup.evaluate(() => {
    const authStatus = document.querySelector('.bg-green-50');
    return authStatus !== null;
  });

  await popup.close();
  return isAuth;
}

/**
 * Clear extension storage
 *
 * @param context Browser context
 */
export async function clearExtensionStorage(
  context: BrowserContext
): Promise<void> {
  const page = await context.newPage();

  // Execute in extension context to clear storage
  await page.evaluate(() => {
    if (typeof chrome !== 'undefined' && chrome.storage) {
      chrome.storage.local.clear();
    }
  });

  await page.close();
}
