/**
 * PlanMyPeak site-control protocol types
 *
 * Defines the wire contract that lets the PlanMyPeak web app drive the
 * extension: detect it, read TrainingPeaks data through it, and ask it to open
 * the import overlay.
 *
 * Two rules are load-bearing and enforced everywhere this protocol is handled:
 *   1. The page names *site-control* request types, never `RuntimeMessage`
 *      types, so the page-reachable surface is this closed union and nothing
 *      else.
 *   2. No credential material (TrainingPeaks token, PlanMyPeak token, Supabase
 *      key, Intervals.icu API key) may appear in any message sent to the page.
 */

import type { Library } from '@/types/api.types';
import type {
  TrainingPlan,
  PlanWorkout,
  CalendarNote,
  CalendarEvent,
} from '@/schemas/trainingPlan.schema';
import type { RxBuilderWorkout } from '@/schemas/rxBuilder.schema';
import type { LibraryItem } from '@/schemas/library.schema';

/**
 * Protocol version carried by every envelope in both directions.
 * The page uses the value reported by `PING` to feature-detect.
 */
export const PLANMYPEAK_SITE_CONTROL_VERSION = 1;

/** Marker on page -> extension messages. */
export const SITE_CONTROL_PAGE_SOURCE = 'planmypeak-site-control';

/** Marker on extension -> page messages. */
export const SITE_CONTROL_EXTENSION_SOURCE = 'planmypeak-extension';

/**
 * The closed set of request types the page may name.
 *
 * Adding an entry here widens what an allowlisted page can make the extension
 * do, so every addition is a deliberate security decision.
 */
export const SITE_CONTROL_REQUEST_TYPES = [
  'PING',
  'GET_LIBRARIES',
  'GET_LIBRARY_ITEMS',
  'GET_TRAINING_PLANS',
  'GET_PLAN_CONTENTS',
  'OPEN_IMPORTER',
] as const;

export type SiteControlRequestType =
  (typeof SITE_CONTROL_REQUEST_TYPES)[number];

export function isSiteControlRequestType(
  value: unknown
): value is SiteControlRequestType {
  return (
    typeof value === 'string' &&
    (SITE_CONTROL_REQUEST_TYPES as readonly string[]).includes(value)
  );
}

export type SiteControlPingPayload = Record<string, never>;

export type SiteControlGetLibrariesPayload = Record<string, never>;

export interface SiteControlGetLibraryItemsPayload {
  libraryId: number;
}

export type SiteControlGetTrainingPlansPayload = Record<string, never>;

export interface SiteControlGetPlanContentsPayload {
  planId: number;
}

export interface SiteControlOpenImporterPayload {
  /** Pre-select this TrainingPeaks library when the overlay opens */
  libraryId?: number;
  /** Pre-select this TrainingPeaks training plan when the overlay opens */
  planId?: number;
}

/** Maps each request type to its payload shape. */
export interface SiteControlPayloadMap {
  PING: SiteControlPingPayload;
  GET_LIBRARIES: SiteControlGetLibrariesPayload;
  GET_LIBRARY_ITEMS: SiteControlGetLibraryItemsPayload;
  GET_TRAINING_PLANS: SiteControlGetTrainingPlansPayload;
  GET_PLAN_CONTENTS: SiteControlGetPlanContentsPayload;
  OPEN_IMPORTER: SiteControlOpenImporterPayload;
}

/**
 * A request envelope posted by the page.
 *
 * `requestId` is generated by the page and echoed verbatim so concurrent
 * requests can be correlated. The extension treats it as an opaque string.
 */
export interface SiteControlRequestEnvelope<T extends SiteControlRequestType> {
  source: typeof SITE_CONTROL_PAGE_SOURCE;
  version: number;
  requestId: string;
  type: T;
  payload: SiteControlPayloadMap[T];
}

/**
 * Discriminated union over `type`, so narrowing a request in a `switch` also
 * narrows its payload.
 */
export type SiteControlRequest = {
  [T in SiteControlRequestType]: SiteControlRequestEnvelope<T>;
}[SiteControlRequestType];

/**
 * Error codes returned to the page.
 *
 * `FORBIDDEN_ORIGIN` exists for completeness of the internal contract only:
 * a non-allowlisted origin is answered with silence, never with this code, so
 * an arbitrary site cannot use the channel to detect the extension.
 */
export type SiteControlErrorCode =
  | 'INVALID_REQUEST'
  | 'UNSUPPORTED_REQUEST_TYPE'
  | 'UNSUPPORTED_VERSION'
  | 'FORBIDDEN_ORIGIN'
  | 'AUTH_REQUIRED'
  | 'API_ERROR'
  | 'INTERNAL_ERROR';

export interface SiteControlError {
  code: SiteControlErrorCode;
  message: string;
}

export interface SiteControlSuccessResponse<TData = unknown> {
  source: typeof SITE_CONTROL_EXTENSION_SOURCE;
  version: number;
  requestId: string;
  ok: true;
  data: TData;
}

export interface SiteControlErrorResponse {
  source: typeof SITE_CONTROL_EXTENSION_SOURCE;
  version: number;
  requestId: string;
  ok: false;
  error: SiteControlError;
}

export type SiteControlResponse<TData = unknown> =
  | SiteControlSuccessResponse<TData>
  | SiteControlErrorResponse;

/**
 * `PING` result.
 *
 * Reports readiness only. Adding any field derived from a token or key to this
 * interface would violate the credential rule above.
 */
export interface SiteControlPingResult {
  protocolVersion: number;
  extensionVersion: string;
  trainingPeaks: { authenticated: boolean };
  planMyPeak: { authenticated: boolean };
}

/**
 * `GET_PLAN_CONTENTS` result — the four plan legs the page always needs
 * together, fetched in one round trip.
 */
export interface SiteControlPlanContentsResult {
  planId: number;
  workouts: PlanWorkout[];
  notes: CalendarNote[];
  events: CalendarEvent[];
  rxWorkouts: RxBuilderWorkout[];
}

export interface SiteControlOpenImporterResult {
  /** True when the overlay was mounted or an existing one was focused */
  opened: boolean;
  /** True when an already-open overlay was focused instead of remounted */
  focused: boolean;
}

/** Maps each request type to its success payload. */
export interface SiteControlResultMap {
  PING: SiteControlPingResult;
  GET_LIBRARIES: Library[];
  GET_LIBRARY_ITEMS: LibraryItem[];
  GET_TRAINING_PLANS: TrainingPlan[];
  GET_PLAN_CONTENTS: SiteControlPlanContentsResult;
  OPEN_IMPORTER: SiteControlOpenImporterResult;
}

/**
 * Extension -> page notification emitted when an import the page requested
 * finishes. Carries counts only, never credential material.
 */
export const SITE_CONTROL_IMPORT_COMPLETED = 'IMPORT_COMPLETED';

export interface SiteControlImportCompletedPayload {
  ok: boolean;
  importedCount: number;
  failedCount: number;
}

export interface SiteControlImportCompletedEvent {
  source: typeof SITE_CONTROL_EXTENSION_SOURCE;
  version: number;
  type: typeof SITE_CONTROL_IMPORT_COMPLETED;
  /** The `OPEN_IMPORTER` request that started this import */
  requestId: string;
  payload: SiteControlImportCompletedPayload;
}
